chore: add README
asyncapi/brand pull request #17
Opened 2021-12-15 21:57 UTC by mcturco

Adding README file as suggested by @alequetzalli 🙌 

If there is anything I should tweak let me know!

(Resolves #14)

2021-12-15 22:06 UTC, mcturco commented
Also - looking at the README in preview mode within the commit and for some reason the image is showing up as broken, but it is linked correctly so I'm not sure why! Here is the preview from VS Code

![Screen Shot 2021-12-15 at 5 04 22 PM](https://user-images.githubusercontent.com/60163079/146272283-efe5f591-4da3-4564-8f8c-bea5ef19ecbe.png)

2021-12-15 23:04 UTC, alequetzalli commented
Hey there! The first thing I would recommend is that you remove all of the unnecessary HTML tags you added because this file is a markdown file so you don't need to put those. 😄 are you familiar with markdown syntax?

https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

2021-12-15 23:16 UTC, alequetzalli commented
> Also - looking at the README in preview mode within the commit and for some reason the image is showing up as broken, but it is linked correctly so I'm not sure why! Here is the preview from VS Code
> 
> 
> 
> ![Screen Shot 2021-12-15 at 5 04 22 PM](https://user-images.githubusercontent.com/60163079/146272283-efe5f591-4da3-4564-8f8c-bea5ef19ecbe.png)
> 
> 

As part of the changes you need to make to remove the HTML tags and use only markdown syntax, I would go ahead and use the markdown syntax for images and see if it's still giving you that broken issue 🙂✌🏽

2021-12-15 23:31 UTC, alequetzalli requested changes

2021-12-15 23:31 UTC, alequetzalli commented on README.md
> +<p>Hi there! Thanks for stopping by Emoji 😄 In this project, we focus on all things related to the creative development of the AsyncAPI brand. The overarching goal for this repo is to provide a space
```suggestion
<p>Hi there! Thanks for stopping by 😄 In this project, we focus on all things related to the creative development of the AsyncAPI brand. The overarching goal for this repo is to provide a space where we can collaborate to define visuals such as logos, colors, typography, iconography, and more! All are welcome to contribute ideas and work where you feel comfortable. Before you submit your contribution, please read our <a href="https://github.com/asyncapi/.github/blob/master/CODE_OF_CONDUCT.md" target="_blank">Code of Conduct</a> and <a href="https://github.com/asyncapi/asyncapi/blob/master/CONTRIBUTING.md#contributing-to-asyncapi" target="_blank">Contribution Guidelines</a>.</p>
```

2021-12-15 23:31 UTC, alequetzalli commented on README.md
> +<p>Join the <a href="https://asyncapi.com/slack-invite" target="_blank">AsyncAPI Slack workspace</a> and the <code>#12_design</code> channel to follow all conversations relating to this repo as well
Do you want to add a `Design` category in our GH Discussions? 
https://github.com/asyncapi/community/discussions 

<img width="1549" alt="Screen Shot 2021-12-15 at 3 30 18 PM" src="https://user-images.githubusercontent.com/19964402/146280829-72bda45b-93f9-4894-9082-5ca90696feca.png">

2021-12-16 14:48 UTC, mcturco commented
Hey @alequetzalli! Thanks! Yeah I was wondering if I should have only used the mark down syntax but I was referencing the [README in the community repo](https://github.com/asyncapi/community/blob/master/README.md?plain=1) and I saw HTML tags so I thought it would be okay!

No worries though, its probably better anyway if I use the correct syntax. I will work on that now and then tag you again when its ready for review! 😄

2021-12-16 15:20 UTC, mcturco commented
@alequetzalli okay! We should be all set now, I updated the format to markdown only 😄

2021-12-16 16:36 UTC, alequetzalli commented
> Hey @alequetzalli! Thanks! Yeah I was wondering if I should have only used the mark down syntax but I was referencing the [README in the community repo](https://github.com/asyncapi/community/blob/master/README.md?plain=1) and I saw HTML tags so I thought it would be okay!


Ahhh I know what you mean... not to throw anyone under the bus but all of those HTML tags for the images and sponsors in the community repo README was made by Lukasz 😂... when I edited that file I only improved it and didn't really take the time to look at fixing that stuff.

I think a good README example is the Initiative's README, from what I remember that one was completely rewritten and cleaned out, so it should only have proper markdown syntax 🙂👍🏽

2021-12-16 16:39 UTC, mcturco commented
@alequetzalli 

> I think a good README example is the Initiative's README, from what I remember that one was completely rewritten and cleaned out, so it should only have proper markdown syntax 🙂👍🏽

Definitely! Yeah I started looking at that one this morning when I was changing up the syntax. I agree with you that the markdown syntax is MUCH cleaner in this case!

2021-12-16 17:41 UTC, alequetzalli commented on README.md
> +## Welcome to the brand ✨
```suggestion
## Welcome to the AsyncAPI brand ✨
```

2021-12-16 17:42 UTC, alequetzalli commented on README.md
> +Hi there! Thanks for stopping by 😄 In this project, we focus on all things related to the creative development of the AsyncAPI brand. The overarching goal for this repo is to provide a space where we
```suggestion
Hi there! Thanks for stopping by. 😄 In this project, we focus on all things related to the creative development of the AsyncAPI brand. The overarching goal for this repo is to provide a space where we can collaborate to define visuals such as logos, colors, typography, iconography, and more! All are welcome to contribute ideas and work where you feel comfortable. Before you submit your contribution, please read our [Code of Conduct](https://github.com/asyncapi/.github/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/asyncapi/asyncapi/blob/master/CONTRIBUTING.md#contributing-to-asyncapi).
```

2021-12-16 17:43 UTC, alequetzalli commented on README.md
> +| :----: | ------------------------------------------ |
For consistency, I would prob pick `&` or `and` throughout. 😀👍🏽

2021-12-16 17:43 UTC, alequetzalli reviewed
Just 2 typos and 1 recommendation :) 

The rest LGTM 🚀

2021-12-16 18:08 UTC, mcturco commented
@alequetzalli thank you! Just committed all your suggestions. LMK if it looks all good!

2021-12-16 18:09 UTC, alequetzalli approved these changes
/rtm

2021-12-16 18:11 UTC, alequetzalli approved these changes

2021-12-16 18:13 UTC, alequetzalli commented
<img width="1217" alt="Screen Shot 2021-12-16 at 10 12 25 AM" src="https://user-images.githubusercontent.com/19964402/146426099-c680f9ad-2ddd-46f0-b301-9bd5cc6047ff.png">

@mcturco  Hmmm... I think something might be off in the settings for this PR? the /rtm script that Lukasz made doesn't seem to work.. and also there is a note that states `you are not authorized to merge` 

what do you think, missy? 🤔

2021-12-16 21:33 UTC, fmvilas approved these changes
:shipit:

2021-12-16 21:33 UTC, merged

2021-12-16 21:35 UTC, fmvilas commented
Only @mcturco and I are code owners of this repo so that's why the /rtm command is not working. I first have to approve.